# Generated by Django 2.0.9 on 2019-03-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
